remote_theme: pmarsceill/just-the-docs
logo: "/img/logo.png"
search_tokenizer_separator: /[\s/]+/
search_enabled: true
heading_anchors: true
aux_links:
  "SmartAnno on GitHub":
    - "//github.com/jianlins/SmartAnno"
footer_content: "Copyright &copy; 2018-2020 Jianlin Shi. Distributed by an <a href=\"https://github.com/jianlins/SmartAnno/blob/master/LICENSE\">Apache license v2.0.</a>"


---
layout: default
title: Customization
nav_order: 4
---